title: Restricted functions
subtitle: Restricted-functions is a package for Python that allows you to deny dangerous functions.
gh-repo: donno2048/restricted-functions
gh-badge: star
theme: jekyll-theme-cayman
