name: Feature request
description: Suggest an idea for this project
title: "[feature request]"
labels: 'enhancement'
assignees:
  - donno2048
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
        Please use Function report for reporting dangerous functions
  - type: textarea
    id: feature
    attributes:
      label: Feature
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/donno2048/restricted-functions/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
