name: Update the docs
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        python -m pip install --upgrade pip
        pip install pdoc3
        pip install .
        pdoc --html ref -f -o docs
        cat README.md | sed "s/\/ref)/\/ref){:target=\"_blank\" rel=\"noopener\"}/" > index.md
        git config --global user.email "just4now666666@gmail.com"
        git config --global user.name "donno2048"
        git add .
        git commit -m "Commit the new docs [GitHub action]"
        git push
