name: OSSAR
on: push
jobs:
  OSSAR-Scan:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: github/ossar-action@v1
      id: ossar
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
